# Generated by Django 2.0.1 on 2018-01-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_stat_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='author',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
