# Generated by Django 2.0.1 on 2018-01-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20180116_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='stat',
            name='author',
            field=models.CharField(blank=True, default='anonymous', max_length=200),
        ),
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stat',
            name='tag',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='stat',
            name='upload',
            field=models.FileField(upload_to='media/'),
        ),
    ]
