# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20180118_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='analyz',
            fields=[
                ('title', models.CharField(blank=True, max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('pfr', models.CharField(blank=True, max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation', models.IntegerField(blank=True)),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
