# Generated by Django 2.0.1 on 2018-02-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20180211_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='pfr',
            fields=[
                ('pfr', models.CharField(blank=True, max_length=1000)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='analyz',
            old_name='relation',
            new_name='id_author',
        ),
        migrations.RemoveField(
            model_name='analyz',
            name='pfr',
        ),
        migrations.AddField(
            model_name='analyz',
            name='log',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='analyz',
            name='out',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
