# Generated by Django 2.0.1 on 2018-02-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20180217_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyz',
            name='log',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='analyz',
            name='out',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
